### ISSUE TITLE
Foundation for Sites 6

### ISSUE THREAD

**Issue by mmjaeger** [g-kanoufi/genesis-foundation-child-theme#1]
Hello
Are you planning to update your theme to Foundation for Sites 6 any time soon?

Thanks

**Comment by g-kanoufi** [comment]
@mmjaeger, Foundation 6 hasn't been (at least publicly) released yet, but as soon as it will be, i intent to make another repo with a new child theme.

**Comment by mmjaeger** [comment]
Sounds good - I've been playing around with Foundation 6 and it's looks
pretty good.

On Thu, Oct 1, 2015 at 8:50 AM, Guillaume Kanoufi notifications@github.com
wrote:

> @mmjaeger https://github.com/mmjaeger, Foundation 6 hasn't been (at
> least publicly) released yet, but as soon as it will be, i intent to make
> another repo with a new child theme.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/g-kanoufi/genesis-foundation-child-theme/issues/1#issuecomment-144769003
> .

## 

Marco M. Jaeger
http://net4visions.com
