### ISSUE TITLE
Foundation 6

### ISSUE THREAD

**Issue by mmjaeger** [g-kanoufi/genesis-foundation-child-theme#3]
hello
was wondering whether you have any plans to update to Foundation 6?

Thanks

**Comment by g-kanoufi** [comment]
Hi there,

Yes, i hope i will have sometime this week so i can push a new repository with foundation 6, i am a bit late, but hopefully this should be ready by friday.
By that time, if you want, you can totally star this repository first :)

Cheers,

## 

Guillaume

**Comment by g-kanoufi** [comment]
One day late, but it's finally [ready](https://github.com/g-kanoufi/genesis-foundation6-child-theme)
